version: '3'
services:
    selenoid:
        platform: linux/x86_64
        image: aerokube/selenoid:latest-release
        container_name: "selenoid"
        network_mode: bridge
        volumes:
            - ./config/browsers.json:/etc/selenoid/browsers.json
            - /var/run/docker.sock:/var/run/docker.sock
            - ./selenoid:/opt/selenoid/video
            - ./logs/selenoid:/opt/selenoid/logs
        environment:
            - TZ=Europe/Moscow
            - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/selenoid
        command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
        expose:
            - "4444"
    selenoid-ui:
        platform: linux/x86_64
        image: aerokube/selenoid-ui
        container_name: "selenoid-ui"
        network_mode: bridge
        links:
            - selenoid
        ports:
            - "8888:8080"
        command: ["--selenoid-uri","http://selenoid:4444"]
    php:
        platform: linux/x86_64
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: php 
        network_mode: bridge
        volumes:
          - ./config/php.ini:/usr/local/etc/php/conf.d/40-custom.ini
          - ./src:/var/www/lenta.events
          - "/var/run/docker.sock:/var/run/docker.sock"   
        links:
          - mysql
          - selenoid
        environment:
          - TZ=Europe/Moscow
          - SELENOID_PORT_4444_TCP_ADDR=selenoid
          - SELENOID_PORT_4444_TCP_PORT=4444
          - MYSQL_PORT_3306_TCP_ADDR=mysql
          - MYSQL_PORT_3306_TCP_PORT=3306
    nginx:
        platform: linux/x86_64
        image: nginx:latest        
        container_name: nginx
        network_mode: bridge
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./config/nginx.conf:/etc/nginx/conf.d/lenta.events.conf
            - ./config/lenta.events.crt:/etc/nginx/ssl/lenta.events.crt
            - ./config/lenta.events.key:/etc/nginx/ssl/lenta.events.key
            - ./src:/var/www/lenta.events
            - ./logs/nginx:/var/log/nginx
        links:
            - php           
    mysql:
        platform: linux/x86_64
        image: mysql:5.7
        command: --character-set-server=utf8 --collation-server=utf8_general_ci
        container_name: mysql
        network_mode: bridge
        ports:
            - "3306:3306"
        volumes:
            - ./config/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./logs/mysql:/var/log/mysql
            - ./mysql:/var/lib/mysql
            - ./data:/tmp/data
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: lenta.events
            MYSQL_ROOT_HOST: '%'